services:
  pingaccess:
    image: pingidentity/pingaccess:2211-7.1.3
    env_file:
      - ${HOME}/.pingidentity/config
    ports:
      - "3000:3000"
      - "9000:9000"
    networks:
      - pingnet
    volumes:
      - pingaccess-out:/opt/out

networks:
  pingnet:

volumes:
  pingaccess-out: